- id: tv_turned_on
  alias: TV turned on
  trigger:
  - platform: state
    entity_id: switch.hdmi_4
    to: 'on'
  action:
  - service: media_player.turn_on
    entity_id: media_player.yamaha
  - service: media_player.select_source
    data:
      entity_id: media_player.yamaha
      source: optical
  - service: rest_command.yamaha_set_speaker
    data:
      speaker: A
      enable: 'true'
  - service: rest_command.yamaha_set_speaker
    data:
      speaker: B
      enable: 'false'
  initial_state: 'on'
  mode: single
- id: tv_turned_off
  alias: TV turned off
  trigger:
  - platform: state
    entity_id: switch.hdmi_4
    to: 'off'
  action:
  - service: media_player.select_source
    data:
      entity_id: media_player.yamaha
      source: spotify
  initial_state: 'on'
  mode: single
- alias: Weekly full snapshot
  id: weekly_full_snapshot
  trigger:
  - platform: time
    at: '3:00:00'
  condition:
  - condition: time
    weekday:
    - mon
  action:
  - service: hassio.snapshot_full
    data_template:
      name: Automated full backup {{ now().strftime('%Y-%m-%d') }}
  - delay:
      minutes: 10
  - service: hassio.addon_stdin
    data:
      addon: 7be23ff5_dropbox_sync
      input:
        command: upload
- alias: Lights on in the evening
  id: lights_on_in_the_evening
  trigger:
  - platform: sun
    event: sunset
    offset: -00:10:00
  condition:
  - condition: state
    entity_id: person.martin
    state: home
  action:
  - service: light.turn_on
    data:
      entity_id: light.center
      transition: 1200
      brightness_pct: 50
  - service: light.turn_on
    data:
      entity_id: light.kitchen_table
      transition: 1200
      brightness: 178
  - service: light.turn_on
    data:
      entity_id: light.kitchen_unit
      transition: 1200
      brightness: 178
  - service: light.turn_on
    data:
      entity_id: light.tv_wall
      transition: 1200
      brightness_pct: 50
  - service: light.turn_on
    data:
      entity_id: light.christmas_lights
- id: sound_controller_volume_down
  alias: Sound Controller Volume Down
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: sound_controller
      event: 3001
  action:
  - service: script.turn_on
    data:
      entity_id: script.volume_down_loop
- id: sound_controller_volume_up
  alias: Sound Controller Volume Up
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: sound_controller
      event: 2001
  action:
  - service: script.turn_on
    data:
      entity_id: script.volume_up_loop
- id: sound_controller_volume_stop
  alias: Sound Controller Volume Stop
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: sound_controller
  condition: '{{ trigger.event.data.event not in [3001, 2001] }}'
  action:
  - service: script.turn_off
    data:
      entity_id: script.volume_up_loop
  - service: script.turn_off
    data:
      entity_id: script.volume_down_loop
- id: sound_controller_switch_yamaha
  alias: Sound Controller Turn On
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: sound_controller
      event: 1002
  condition:
  - condition: state
    entity_id: media_player.yamaha
    state: 'off'
  action:
  - service: media_player.turn_on
    data:
      entity_id: media_player.yamaha
  mode: single
- id: lights_off
  alias: Lights off
  trigger:
  - platform: state
    entity_id: person.martin
    to: not_home
  - platform: time
    at: '4:00:00'
  action:
  - service: light.turn_off
    entity_id: all
- id: freezer_open_alert
  alias: Freezer Open Alert
  trigger:
    platform: state
    entity_id: binary_sensor.freezer_door
    to: 'on'
    for: 00:10:00
  action:
  - service: persistent_notification.create
    data:
      title: Freezer open for over 10 minutes
      message: Freezer open for over 10 minutes.
      notification_id: freezer_open_alert
  - service: notify.email
    data:
      title: Freezer open for over 10 minutes
      message: Freezer open for over 10 minutes.
- id: '1607179755688'
  alias: Turn off heating
  description: ''
  trigger:
  - platform: time
    at: input_datetime.heating_off_time
  condition: []
  action:
  - service: climate.turn_off
    data: {}
    entity_id: climate.heating
  mode: single
- id: '1607525870870'
  alias: Sound Controller Pause/Resume Spotify
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: sound_controller
      event: 1002
  condition: '{{ is_state_attr(''media_player.yamaha'', ''source'', ''spotify'')
    }}'
  action:
  - service: media_player.media_play_pause
    data:
      entity_id: media_player.yamaha
  mode: single
- id: '1607526213723'
  alias: Sound Controller Mute/Unmute
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: sound_controller
      event: 1002
  condition: '{{ not is_state(''media_player.yamaha'', ''off'') and not is_state_attr(''media_player.yamaha'',
    ''source'', ''spotify'') }}'
  action:
  - service: media_player.volume_mute
    data:
      entity_id: media_player.yamaha
      is_volume_muted: '{{ is_state_attr(''media_player.yamaha'', ''is_volume_muted'',
        false) }}'
  mode: single
- id: nightstand_switch_all_off
  alias: Nightstand Switch All Off
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bedroom_nightstand_switch
      event: 2002
  condition:
  - condition: state
    entity_id: light.bedroom_lights
    state: 'off'
  action:
  - service: light.turn_off
    entity_id: all

- id: tasmota_on
  alias: Tasmota On
  initial_state: false
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bedroom_nightstand_switch
      event: 2001
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/tasmota1/POWER
      payload: on

- id: tasmota_off
  alias: Tasmota Off
  initial_state: false
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bedroom_nightstand_switch
      event: 2003
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/tasmota1/POWER
      payload: off

- id: tasmota_on_off
  alias: Tasmota On Off
  initial_state: false
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bedroom_nightstand_switch
      event: 2002
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/tasmota1/POWER
      payload: on
  - delay:
      seconds: 2
  - service: mqtt.publish
    data:
      topic: cmnd/tasmota1/POWER
      payload: off
