- alias: TV turned on
  id: tv_turned_on
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: switch.hdmi_4
    to: 'on'
  action:
  - service: media_player.turn_on
    entity_id: media_player.yamaha_main
  - service: media_player.select_source
    data:
      entity_id: media_player.yamaha_main
      source: optical
- alias: TV turned off
  id: tv_turned_off
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: switch.hdmi_4
    to: 'off'
  action:
  - service: media_player.select_source
    data:
      entity_id: media_player.yamaha_main
      source: spotify
- alias: Weekly full snapshot
  id: weekly_full_snapshot
  trigger:
  - platform: time
    at: '3:00:00'
  condition:
  - condition: time
    weekday:
    - mon
  action:
  - service: hassio.snapshot_full
    data_template:
      name: Automated full backup {{ now().strftime('%Y-%m-%d') }}
  - delay:
      minutes: 10
  - service: hassio.addon_stdin
    data:
      addon: 7be23ff5_dropbox_sync
      input:
        command: upload
- alias: Lights on in the evening
  id: lights_on_in_the_evening
  trigger:
  - platform: sun
    event: sunset
    offset: -00:10:00
  condition:
  - condition: state
    entity_id: person.martin
    state: home
  action:
  - service: light.turn_on
    data:
      entity_id: light.center
      transition: 1200
      brightness: 128
  - service: light.turn_on
    data:
      entity_id: light.kitchen_table
      transition: 1200
      brightness: 178
  - service: light.turn_on
    data:
      entity_id: light.bar
      transition: 1200
      brightness: 178
  - service: light.turn_on
    data:
      entity_id: light.kitchen_desk
      transition: 1200
      brightness: 178

- id: sound_controller_volume_down
  alias: Sound Controller Volume Down
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: sound_controller
      event: 3001  # rotate left
  action:
    - service: script.turn_on
      data:
        entity_id: script.volume_down_loop
- id: sound_controller_volume_up
  alias: Sound Controller Volume Up
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: sound_controller
      event: 2001  # rotate right
  action:
    - service: script.turn_on
      data:
        entity_id: script.volume_up_loop
- id: sound_controller_volume_stop
  alias: Sound Controller Volume Stop
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: sound_controller
  condition: "{{ trigger.event.data.event not in [3001, 2001] }}"
  action:
    - service: script.turn_off
      data:
        entity_id: script.volume_up_loop
    - service: script.turn_off
      data:
        entity_id: script.volume_down_loop
- id: sound_controller_switch_yamaha
  alias: Sound Controller Switch Yamaha
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: sound_controller
      event: 1002  # button click
  action:
    - service: media_player.toggle
      entity_id: media_player.yamaha_main

- id: lights_off
  alias: Lights off
  trigger:
  - platform: state
    entity_id: person.martin
    to: not_home
  - platform: time
    at: '4:00:00'
  action:
  - service: light.turn_off
    entity_id: all
