title: Home
views:
  - badges: []
    cards:
      - type: vertical-stack
        cards:
          - entity: media_player.yamaha
            type: custom:mini-media-player
            max_volume: 60
            shortcuts:
              columns: 3
              column_height: 30
              buttons:
                - name: A
                  type: service
                  id: script.yamaha_set_speaker
                  data:
                    speakerA: 'true'
                    speakerB: 'false'
                - name: B
                  type: service
                  id: script.yamaha_set_speaker
                  data:
                    speakerA: 'false'
                    speakerB: 'true'
                - name: A+B
                  type: service
                  id: script.yamaha_set_speaker
                  data:
                    speakerA: 'true'
                    speakerB: 'true'
                - name: Worldwide FM
                  type: playlist
                  id: presets:1
                - name: Radio Wave
                  type: playlist
                  id: presets:2
          - type: media-control
            entity: media_player.apple_tv_2
          - entities:
              - entity: light.center
                toggle: true
                type: custom:slider-entity-row
              - entity: light.tv_wall
                toggle: true
                type: custom:slider-entity-row
              - entity: light.christmas_lights
              - entity: light.kitchen_table
                name: Table
                toggle: true
                type: custom:slider-entity-row
              - entity: light.kitchen_unit
                toggle: true
                type: custom:slider-entity-row
              - entity: light.bedroom_nightstand
                toggle: true
                type: custom:slider-entity-row
              - entity: light.hue_go
                toggle: true
                type: custom:slider-entity-row
              - entity: light.hall
              - entity: light.staircase
                toggle: true
                type: custom:slider-entity-row
            title: Light
            type: entities
      - type: vertical-stack
        cards:
          - type: custom:mini-graph-card
            entities:
              - entity: sensor.outside_temperature
                name: Outside
            hours_to_show: 24
            points_per_hour: 2
            hour24: true
            show:
              extrema: true
              fill: false
          - type: custom:mini-graph-card
            name: Inside
            entities:
              - entity: sensor.living_room_temperature
                name: Living Room
                state_adaptive_color: true
                show_fill: false
              - entity: sensor.staircase_temperature
                name: Staircase
                show_state: true
                state_adaptive_color: true
                show_fill: false
              - entity: sensor.bedroom_temperature
                name: Bedroom
                show_state: true
                state_adaptive_color: true
                show_fill: false
              - entity: sensor.attic_temperature
                name: Attic
                show_state: true
                state_adaptive_color: true
                show_fill: false
              - color: grey
                entity: sensor.heating_action
                name: Heating
                show_line: false
                show_points: false
                show_legend: true
                show_fill: true
                y_axis: secondary
                smoothing: false
            hours_to_show: 24
            points_per_hour: 2
            hour24: true
            icon: mdi:thermometer
            show:
              legend: true
              fill: true
              extrema: true
      - type: vertical-stack
        cards:
          - type: weather-forecast
            entity: weather.dark_sky
          - type: entities
            entities:
              - entity: cover.all_blinds
                name: All Blinds
              - type: divider
              - entity: cover.blind1
                name: Bedroom
              - entity: cover.blind2
                name: Living Room
              - entity: cover.blind3
                name: Kitchen
            title: Blinds
          - entity: climate.heating
            type: custom:simple-thermostat
            header:
              toggle:
                entity: switch.heating_on
            layout:
              step: row
            control: false
            step_layout: row
            hide:
              temperature: true
              state: true
          - type: entities
            entities:
              - entity: input_boolean.heat_in_the_morning
              - entity: automation.turn_off_heating
              - entity: input_datetime.heating_off_time
                name: At Time
      - type: vertical-stack
        cards:
          - entities:
              - entity: person.martin
              - entity: switch.home
            title: ''
            type: entities
          - type: entities
            entities:
              - entity: binary_sensor.main_door
              - entity: binary_sensor.freezer_door
    path: default_view
    title: Home
  - title: Misc
    path: misc
    badges: []
    cards:
      - detail: 2
        entity: sensor.outside_temperature_delay
        name: Outside Temperature Delay
        type: sensor
      - type: entities
        entities:
          - entity: remote.apple_tv_2
      - entities:
          - entity: switch.hdmi_4
            name: Apple TV
          - entity: switch.hdmi_0
            name: Panasonic TV
        show_header_toggle: true
        title: HDMI CEC
        type: entities
      - type: media-control
        entity: media_player.yamaha
