title: Home
views:
  - badges: []
    cards:
      - entities:
          - entity: light.center
            toggle: true
            type: 'custom:slider-entity-row'
          - entity: light.kitchen_table
            name: Table
            toggle: true
            type: 'custom:slider-entity-row'
          - entity: light.bar
            toggle: true
            type: 'custom:slider-entity-row'
          - entity: light.kitchen_desk
            name: Hue Strip
            toggle: true
            type: 'custom:slider-entity-row'
          - entity: light.hall
        title: Light
        type: entities
      - type: custom:mini-graph-card
        entities:
          - sensor.outside_temperature
        hours_to_show: 24
        points_per_hour: 2
        hour24: true
        show:
          extrema: true
      - detail: 2
        entity: sensor.outside_temperature_delay
        name: Outside Temperature Delay
        type: sensor
      - type: custom:mini-graph-card
        entities:
          - sensor.living_room_temperature
        hours_to_show: 24
        points_per_hour: 2
        hour24: true
        icon: 'mdi:thermometer'
        show:
          extrema: true
      - type: custom:mini-graph-card
        entities:
          - sensor.0x00158d0004873fc9_temperature
        hours_to_show: 24
        points_per_hour: 2
        decimals: 1
        hour24: true
        icon: 'mdi:thermometer'
        show:
          extrema: true
      - type: weather-forecast
        entity: weather.dark_sky
      - entity: climate.living_room
        type: 'custom:simple-thermostat'
        control:
          - hvac
      - entity: media_player.yamaha_main
        type: media-control
      - entities:
          - person.martin
        title: ''
        type: entities
      - entities:
          - entity: switch.hdmi_4
            name: Apple TV
          - entity: switch.hdmi_0
            name: Panasonic TV
        show_header_toggle: true
        title: HDMI CEC
        type: entities
      - type: entities
        entities:
          - entity: input_boolean.zigbee_permit_join
          - entity: timer.zigbee_permit_join
          - entity: sensor.bridge_state
        show_header_toggle: false
        title: Zigbee
      - type: entity
        entity: binary_sensor.door_contact
        name: Main Door
      - type: entity
        entity: binary_sensor.freezer_contact
        name: Freezer
    path: default_view
    title: Home
